services:
  - type: web
    name: artist
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn sketch_project.wsgi"
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sketch_project.settings
      - key: PYTHON_VERSION
        value: 3.11
