services:
  - type: web
    name: artist
    env: python
    buildCommand: "pip install -r requirements.txt"
    rootDir: sketch_project
    startCommand: gunicorn sketch_project.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: sketch_project.settings
      - key: PYTHON_VERSION
        value: 3.11
